services:
  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: lynxpass
    depends_on:
      - db
    cpus: 0.5
    mem_limit: 512m

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    command: ["--lower-case-table-names=1"]
    environment:
      MARIADB_ROOT_PASSWORD: lynxpass
    cpus: 0.5
    mem_limit: 512m
